version: '2'
services:
    minemeld:
        image: kidmose/minemeld
        ports:
            - '8443:443'
            - '13514'
        volumes:
            - minemeld-local:/opt/minemeld/local
        tmpfs: /run

volumes:
    minemeld-local:
